name: Branch Deleted
on: delete
jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          GITHUB_REF_NAME=${{ github.event.ref }}
          echo "Clean up for branch ${{ github.event.ref }}"
          echo ${GITHUB_REF_NAME}
          echo ${GITHUB_EVENT_REF}